### ISSUE TITLE
Date picker - Add labequipment 

### ISSUE THREAD

**Issue by Sahaswari** [riyajidevindu/ERP_New_MicroServices#8]
Date picker -  the date not coming for the lab equipment list

**Comment by riyajidevindu** [comment]
The issue was fixed. Now it is fine. The data binding method is wrong in that. That was the issue. Following is the commit detail
[DatePicker Issue Fix](https://github.com/riyajidevindu/ERP_New_MicroServices/pull/9/commits/757f409f65b055cac274fc1252c04e547e449d63)

**Comment by Sahaswari** [comment]
Thank you for that.
